version : '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible/docker
    build:
      context: pipeline
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - test_network
  remote_host:
    container_name: remote_host
    image: remote-host
    build: 
       context: centos
    volumes:
      - "$PWD/aws_s3.sh:/tmp/aws_s3.sh"
    networks:
      - test_network
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - test_network
  web:
    container_name: web
    image: ansible-web
    build:
      context: jenkins-ansible/web
    ports:
      - "80:80"
    networks:
      - test_network 
networks:
  test_network:
    driver: bridge 
