pipeline {

    agent any
    
    environment {
        PASS = credentials('registry-pass') 
    }

    stages {
        // stage('checkout'){
        //     steps {
        //         git branch: 'main', credentialsId: '35319474-9ee1-4abc-85ae-64c68114f4de', url: 'https://github.com/grim-knight/jenkins_docker_maven.git'
        //     }
        // }
        stage('Build') {
            steps {
                sh '''
                    pwd
                    ls -a
                    pwd
                    ./pipeline/jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    pwd
                    ls -a
                    ./pipeline/jenkins/build/build.sh
                    pwd
                '''
            }

            post {
                success {
                   archiveArtifacts artifacts: 'pipeline/java-app/target/*.jar', fingerprint: true
                }
            }
        }

        stage('Test') {
            steps {
                sh '''
                pwd
                ./pipeline/jenkins/test/mvn.sh mvn test'''
            }

            post {
                always {
                    junit 'pipeline/java-app/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Push') {
            steps {
                sh './pipeline/jenkins/push/push.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh './pipeline/jenkins/deploy/deploy.sh'
            }
        }
    }
}
